package com.zh.ssm.mapper;

import com.zh.ssm.pojo.AuthRoleExample;
import com.zh.ssm.pojo.AuthRoleKey;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface AuthRoleMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table auth_role
     *
     * @mbggenerated Mon Oct 17 22:31:16 CST 2022
     */
    int countByExample(AuthRoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table auth_role
     *
     * @mbggenerated Mon Oct 17 22:31:16 CST 2022
     */
    int deleteByExample(AuthRoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table auth_role
     *
     * @mbggenerated Mon Oct 17 22:31:16 CST 2022
     */
    int deleteByPrimaryKey(AuthRoleKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table auth_role
     *
     * @mbggenerated Mon Oct 17 22:31:16 CST 2022
     */
    int insert(AuthRoleKey record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table auth_role
     *
     * @mbggenerated Mon Oct 17 22:31:16 CST 2022
     */
    int insertSelective(AuthRoleKey record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table auth_role
     *
     * @mbggenerated Mon Oct 17 22:31:16 CST 2022
     */
    List<AuthRoleKey> selectByExample(AuthRoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table auth_role
     *
     * @mbggenerated Mon Oct 17 22:31:16 CST 2022
     */
    int updateByExampleSelective(@Param("record") AuthRoleKey record, @Param("example") AuthRoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table auth_role
     *
     * @mbggenerated Mon Oct 17 22:31:16 CST 2022
     */
    int updateByExample(@Param("record") AuthRoleKey record, @Param("example") AuthRoleExample example);
}