package com.zh.ssm.pojo;

import java.io.Serializable;

public class Auth implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_auth.aid
     *
     * @mbggenerated Sat Oct 15 15:57:34 CST 2022
     */
    private Integer aid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_auth.path
     *
     * @mbggenerated Sat Oct 15 15:57:34 CST 2022
     */
    private String path;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_auth.name
     *
     * @mbggenerated Sat Oct 15 15:57:34 CST 2022
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_auth
     *
     * @mbggenerated Sat Oct 15 15:57:34 CST 2022
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_auth.aid
     *
     * @return the value of t_auth.aid
     *
     * @mbggenerated Sat Oct 15 15:57:34 CST 2022
     */
    public Integer getAid() {
        return aid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_auth.aid
     *
     * @param aid the value for t_auth.aid
     *
     * @mbggenerated Sat Oct 15 15:57:34 CST 2022
     */
    public void setAid(Integer aid) {
        this.aid = aid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_auth.path
     *
     * @return the value of t_auth.path
     *
     * @mbggenerated Sat Oct 15 15:57:34 CST 2022
     */
    public String getPath() {
        return path;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_auth.path
     *
     * @param path the value for t_auth.path
     *
     * @mbggenerated Sat Oct 15 15:57:34 CST 2022
     */
    public void setPath(String path) {
        this.path = path == null ? null : path.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_auth.name
     *
     * @return the value of t_auth.name
     *
     * @mbggenerated Sat Oct 15 15:57:34 CST 2022
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_auth.name
     *
     * @param name the value for t_auth.name
     *
     * @mbggenerated Sat Oct 15 15:57:34 CST 2022
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_auth
     *
     * @mbggenerated Sat Oct 15 15:57:34 CST 2022
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        Auth other = (Auth) that;
        return (this.getAid() == null ? other.getAid() == null : this.getAid().equals(other.getAid()))
            && (this.getPath() == null ? other.getPath() == null : this.getPath().equals(other.getPath()))
            && (this.getName() == null ? other.getName() == null : this.getName().equals(other.getName()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_auth
     *
     * @mbggenerated Sat Oct 15 15:57:34 CST 2022
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getAid() == null) ? 0 : getAid().hashCode());
        result = prime * result + ((getPath() == null) ? 0 : getPath().hashCode());
        result = prime * result + ((getName() == null) ? 0 : getName().hashCode());
        return result;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_auth
     *
     * @mbggenerated Sat Oct 15 15:57:34 CST 2022
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", aid=").append(aid);
        sb.append(", path=").append(path);
        sb.append(", name=").append(name);
        sb.append("]");
        return sb.toString();
    }
}